# This program is used to compare a list of client emails, client names, and client "Account Names"
# Vs. my client list.  (march.csv vs. tomOrders.csv.  You can use test CSV files generated by Excel. UTF8.)

import csv

# Opens both files
with open("march.csv", encoding='utf8') as marchfile:
    with open("tomOrders.csv", encoding='utf8') as tomOrder:

# Calls the 'reader' method of the csv function, with the excel dialect and separated by commas
        readCSV = csv.reader(marchfile, dialect='excel', delimiter=',')
        readTOM = csv.reader(tomOrder, dialect='excel', delimiter=',')

        companies = []  # Original Lists
        names = []
        epromosEmails = []
        companiesTom = []
        namesTom = []
        originalEmailsTom = []


        for row in readCSV: # Iterates through the rows in the excel doc for the specified row in brackets.

            company = row[10]
            name = row[11]
            excelEmail = row[12]

            companies.append(company) # Append the original lists above
            names.append(name)
            epromosEmails.append(excelEmail)

        for row in readTOM:

            companyTom = row[5]
            nameTom = row[3]
            excelEmailTom = row[4]

            companiesTom.append(companyTom) # Append the original lists above
            namesTom.append(nameTom)
            originalEmailsTom.append(excelEmailTom)

# Uses the .split method to get: domain name from emails, split the company names per word, and retrieves
# Last name
        epromosEmailsDomains = [x.split('@')[1] for x in epromosEmails if '@' in x] #others emails
        tomEmailsDomains = [x.split('@')[1] for x in originalEmailsTom if '@' in x] #my emails
        epromosCompanySplit = [y.split(' ')[0] for y in companies]
        tomCompanySplit = [y.split(' ')[0] for y in companiesTom]
        epromosNameSplit = [z.split(' ')[-1] for z in names]

# Compares the lists as sets with &
        emailSplitMatches = set(epromosEmailsDomains) & set(tomEmailsDomains)
        companySplitMatches = set(epromosCompanySplit) & set(tomCompanySplit)
        lastNameMatches = set(epromosNameSplit) & set(namesTom)


    print(lastNameMatches)

marchfile.close()
